### ISSUE TITLE
Cover page with lots of voters overflows the page

### ISSUE THREAD

**Issue by jeffkole** [sjforman/votefwd#129]
An example says 1000 words.

[2018-09-13-votefwd-letters-batch-of-100 (3).pdf](https://github.com/sjforman/votefwd/files/2380584/2018-09-13-votefwd-letters-batch-of-100.3.pdf)

**Comment by sjforman** [comment]
Looking at the cover page for another reason, and thinking about how to fix this. 

I don't see a way to handle it in the template itself — by the time we're dealing with html, inserting page breaks where needed doesn't appear to be possible.  

I think probably the best way is to limit the cover page to 25 voters, and generate `numvoters % 25` cover pages. I would probably include the front matter (return address and whatnot) on each page. Also convenient, because multiple cover pages can become handouts at letter parties.

**Comment by sjforman** [comment]
Done via #201
