### ISSUE TITLE
Unable to download letters on iPad

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#153]
The "download all" and "Download letter" functions silently fail on both Safari and Chrome on an iPad running iOS 11.4. 

After pressing the button a few times, a dialog box appears warning that the website is "repeatedly trying to open a separate app," or something to that effect. Clicking "allow" does not cause the PDF to be downloaded.

Tried plugging the iPad into a desktop and inspecting the Safari developer console — no errors evident.

**Comment by heyitsgarrett** [comment]
So, still looking at! I need to call it quits soon, but what I've learned so far is:
– Blob won't work since it's a web service api and this is a node server, [as far as I can tell](https://github.com/foliojs/pdfkit/issues/625)
– BUT, in looking at that link above, I'm going to try `pdfkit` next [in this function](https://github.com/sjforman/votefwd/blob/ipad_download_issue_153/server/server.js#L112-L133)

Will find some time tomorrow to check it out some more 🤘

**Comment by sjforman** [comment]
Thanks for looking into it @heyitsgarrett!

**Comment by asterns** [comment]
@sjforman @heyitsgarrett Planning to try the approach described here: https://github.com/hueniverse/hawk#single-uri-authorization - downloading a pdf would become two steps run in sequence: 
1) for a user with the appropriate access, generate a cryptographically secure short-lived url that can dynamically generate the pdf 
2) call that url to download the pdf

Let me know if you've already solved this issue or have any concerns about this approach.

**Comment by sjforman** [comment]
@asterns, that sounds good to me! We have not previously done what you're suggesting. 

We did previously generate long-lived PDFs, store them, and then when a user would try to download a single letter, they'd be downloading that file (via a signed URL) rather than receiving a blob into the browser. This _did_ work on iOS, but we abandoned it because it was (a) very resource intensive, and (b) wasn't a reasonable approach (and was never even actually implemented) for the "download bundle" use case, which is the most common pattern. Just sharing this by way of background, I don't think it's directly relevant to what you're suggesting, which, again, sounds like a good approach to me.

**Comment by jeffkole** [comment]
Odd that the signed URL would make a difference.  @asterns please keep us up to date on your progress in this ticket.  I think I'll have some time this week to work on it, so let me know if you want help or to hand stuff off.

**Comment by asterns** [comment]
@jeffkole @sjforman added https://github.com/sjforman/votefwd/pull/176 to address the issue.  Please review.  The fix does a `window.open` which flashes a new tab which quickly disappears in most browsers, but stays open on chrome in ipad.  We could get fancier to try to detect if the browser supports blob and then do it the old way if so - but it seemed better to prioritize function over form in this case.  @jeffkole - to your point about the signed URL making a difference - it's not that that a signed URL fixes the issue, it's the "window.open" to a url that fixes it, it's just that a signed URL becomes necessary to make the pdf secure since you can no longer pass the access token as with the previous approach.

**Comment by jeffkole** [comment]
Ok, that makes more sense.  Any chance that setting the "content-type" header to "application/pdf" would have solved it without having to open a new window and all?

**Comment by asterns** [comment]
@jeffkole - possible that might have worked, I didn't try it.  I got the impression that the IPad wasn't able to handle "blob" responseType but perhaps setting content-type would have fixed it.  But it seems like the IPad tries to avoid downloading files to the device at all costs, so I think opening it in another window actually makes it easier to print on an IPad.  Unfortunately, I no longer have access to an IPad this week so can't easily test it.  Might be worth trying if you want to.
