### ISSUE TITLE
Signal to users when voter adoption is successful

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#205]
Problem: Users on smaller screens or with voters already in their lists may not notice when new voters have been adopted. They click the "adopt" button multiple times, accidentally inflating their list of voters and requiring admin intervention to fix. 

Current behavior: When users click the "Adopt 5 voters" or "Adopt 25 votes" button, the button state changes to disabled while the XHR request is called, and returns to normal state 0.5 seconds after a successful adoption -- but there is no other signal that the voters were successfully adopted and added to the list of "Letters to Prepare."

Proposed behavior: Clearly signal to a user when an adoption is successful, and discourage multiple clicks in rapid succession.

Some implementation ideas:

1.  Scroll the user's browser window to the "Letters to Prepare" section upon successful adoption
2. Change the button text to "Adopted!" for ~2 seconds when the request is successful
3. Prevent multiple button presses within ~10 seconds of a successful adoption (e.g., pop a modal window asking for confirmation)

I think #1 is probably most straightforward and all that is likely needed. This [SO question](https://stackoverflow.com/questions/43441856/reactjs-how-to-scroll-to-an-element#43442830) feels like it's in the right direction (see `adoptVoter()` in `AdoptVoter.js`).

**Comment by sjforman** [comment]
Thanks for opening this, @jimwebb. Totally agree that something needs to be done to address this. Have noticed that people often have this problem, but hadn't really thought deeply about why, probably because I'm usually using a full-screen browser, so it's more obvious that the number of adopted voters has changed, because it's visible. I'm not totally sure what the right solution is, and I'm a little reluctant to make it *that* much more difficult to adopt multiple batches in rapid succession, because I know that a lot of super-volunteers are kind of relying on that capability. So I wonder if it might suffice to just make the number of voters in your "queue" much more prominent. Will sleep on it and then take a look tomorrow morning. Thanks again for summing this problem up so clearly.

**Comment by bbrodsky** [comment]
Perhaps right below the two adopt buttons, there could be a "Total Voters Adopted" counter?

**Comment by sjforman** [comment]
@bbrodsky Yup, I think that sounds like a good solution. I poked at it with a small viewport and I think the other thing you could do is to just shrink and remove some things for viewport < s. Like, the description of the district isn't essentially, could just hide that. Maybe shrink the padding and shorten some of the text, again conditionally. I took a quick stab at these last night, and I have it kinda working in a branch, but not all of it is conditional yet. Here, in case useful as starting point: https://github.com/sjforman/votefwd/tree/more-obvious-adoption-success

**Comment by sjforman** [comment]
Addressed (hopefully satisfactorily) by #222
