### ISSUE TITLE
Reminder emails!

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#236]
# Background

We should probably send a bunch of email reminders to people to tell them to (a) make sure to either complete their letters, or if they absolutely cannot, let us know so we can relinquish them, and (b) send them on the right date. Scope of this project is to find a way to send the right emails to the right people. 

# Draft plan / targeting / timing

I think we should plan to send two different types of emails. 

## "Please prep"

Content: "Make sure you complete your letters that you have adopted but not yet marked 'prepped'"! Would also include a reminder about how to log in to mark them "prepped," an indicator of which identity provider to use to log in (so people who have multiple accounts don't get mixed up — see also #235), and a strong statement that it is your obligation to complete these, but if you absolutely cannot, to please let us know by sending an email to help@votefwd.org with a specific subject line. 

Targeting: Everyone who has at least 1 voter "adopted" but not yet marked "prepped." 

Timing: Once per day from the day this goes live until October 29. 

## "Please send"

Content: "Send your letters on October 30 and mark them 'sent' in the app". Would also include a reminder about how to do this, identity provider to use to log in, and a reminder that it's an obligation + what to do if you're unable to follow through. 

Targeting: Everyone who has at least one voter adopted. 

Timing: Once each on October 28, 29, 30, and 31st. 

# Unsubscribe

We probably need a way to allow people to unsubscribe. But if we're sending these to folks who have adopted a voter, we can't really let them unsubscribe without telling us what happened with the voters they adopted. Low-tech solution might just be to add some questions about this to the manual / hacked-together Google form at http://bitly.com/votefwd-unsubscribe. 

# Implementation

This will be the first time that we're sending batch, rather than transactional, emails, so we'll probably have to have a service for that. A couple ideas: 

1) Pre-draft all these emails and have them be sent on autopilot on a schedule without manual intervention. Pro: no UI to build. Con: less flexible, as it's likely that we will find that we have to send additional emails and that we'll want to change the content over time, in ways we can't currently predict. 

2) Add an ad-hoc email-sending capability at, say, `/admin/email`, with some kind of text-entry field (can presume the user will be willing / able to input html markup), a way to choose a "target (which pool of users to send to)", a "send" button, a "are you really sure? you're about to send this email to xxx users," and confirmation. 

In either case, we may want to also start keeping track of which emails we've sent to which users and when.

**Comment by asterns** [comment]
Sorry about the duplicate messages - GitHub kept swallowing my comments and not displaying them for hours so I thought they had not been posted.

**Comment by jimwebb** [comment]
Just talking here, but another subset of users that could need special handling might be users with LOTS of letters (say, 200+). There are about 300-400 of these users. I could imagine wanting to say:

- Wow, thank you, you're in the hall of fame?
- Do you need any extra help with the website (e.g., is everything okay)?
- Are you a real person and not a voter-stealing bot (that's a question for us, not them, but if there are weird outliers with hundreds of adopted but not-prepared or not-sent voters, we might want to keep an eye on them and reach out separately)?
- Can you send us a photo of your stash that we can use on social media?

This might be a hand-pulled list rather than something programmatically built, and it's easy enough to sort by voters in the current [admin screens](https://votefwd.org/admin/). Just wanted to make the suggestion.

**Comment by sjforman** [comment]
Closed by #248. Thanks!
